apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/asenmx/homelab
    path: charts/cert-manager
    targetRevision: test
    helm:
      releaseName: cert-manager
      valueFiles:
      - argocd/infra/cert-manager/values.yaml 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
