image:
  repository: asnm/gtp-poc 
  pullPolicy: IfNotPresent
  tag: 4ec34985a1256c61018d49e2cc74e174dfd83c49 

imagePullSecrets:
- name: regcred


service:
  type: ClusterIP
  port: 8081

httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: istio-gateway
    sectionName: http
  hostnames:
  - gtp.k8s.labz
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

