image:
  repository: asnm/gtp-poc 
  pullPolicy: IfNotPresent
  tag: sha-de5d768

imagePullSecrets:
- name: regcred


service:
  type: ClusterIP
  port: 8081

httpRoute:
  enabled: true 
  annotations: {}
  parentRefs:
  - name: istio-gateway
    sectionName: http
    namespace: istio-system
  hostnames:
  - gtp.k8s.labz
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
livenessProbe:
  httpGet:
    path: /
    port: 8081
readinessProbe:
  httpGet:
    path: /
    port: 8081

